// user
export {
  UPDATE_USER,
  QUERY_USER_LIST,
  QUERY_USER_LIST_FOR_OPTIONS,
  LOGIN,
  QYWX_CODE_LOGIN,
  QUERY_USER,
  CREATE_USER,
  LOGOUT,
  RESET_PASSWORD,
  HANDOVER_INFO,
  RESIGN,
  CHANGE_PASSWORD,
} from "./user.graphql";
